name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
    Test-Job:
        runs-on: ubuntu-latest
        steps:
          - run: echo "whoami"
          - name: this is test
            run: echo "hello"